// Auto-generated by /data-contract-generator
// @spec FEAT-001/DM-001, FEAT-001/DM-002, FEAT-002/DM-001, FEAT-002/DM-002, FEAT-003/DM-001
// Do not edit manually - regenerate from specs

import { z } from 'zod';

// User schemas
export const UserSchema = z.object({
  id: z.string().uuid(),
  email: z.string().email().max(255),
  email_verified: z.boolean().default(false),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

export const UserResponseSchema = UserSchema.pick({
  id: true,
  email: true,
});

// Auth request schemas
export const RegisterRequestSchema = z
  .object({
    email: z.string().email().max(255),
    password: z.string().min(12),
    password_confirm: z.string(),
  })
  .refine((data) => data.password === data.password_confirm, {
    message: "Passwords don't match",
    path: ['password_confirm'],
  });

export const LoginRequestSchema = z.object({
  email: z.string().email(),
  password: z.string().min(1),
});

export const VerifyEmailRequestSchema = z.object({
  token: z.string().min(1),
});

export const RefreshTokenRequestSchema = z.object({
  refresh_token: z.string().min(1),
});

// Auth response schemas
export const TokenResponseSchema = z.object({
  access_token: z.string(),
  refresh_token: z.string(),
  token_type: z.literal('Bearer'),
  expires_in: z.number().default(3600),
  user: UserResponseSchema,
});

export const AccessTokenResponseSchema = z.object({
  access_token: z.string(),
  token_type: z.literal('Bearer'),
  expires_in: z.number().default(3600),
});

export const MessageResponseSchema = z.object({
  message: z.string(),
});

export const ErrorResponseSchema = z.object({
  error: z.string(),
  message: z.string().optional(),
  details: z
    .array(
      z.object({
        field: z.string(),
        message: z.string(),
      })
    )
    .optional(),
});

// Session schemas @spec FEAT-002/DM-001
export const SessionSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  refresh_token_hash: z.string(),
  user_agent: z.string().nullable().optional(),
  ip_address: z.string().nullable().optional(),
  created_at: z.string().datetime(),
  expires_at: z.string().datetime(),
  revoked_at: z.string().datetime().nullable().optional(),
});

// Login Attempt schemas @spec FEAT-002/DM-002
export const LoginAttemptSchema = z.object({
  id: z.string().uuid(),
  email: z.string().email().max(255),
  ip_address: z.string().nullable().optional(),
  success: z.boolean(),
  created_at: z.string().datetime(),
});

// Email Verification Token schemas @spec FEAT-001/DM-002
const hexToken64 = z.string().regex(/^[a-f0-9]{64}$/, 'Token must be 64 hex characters');

export const EmailVerificationTokenSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  token: hexToken64,
  expires_at: z.string().datetime(),
  used_at: z.string().datetime().nullable().optional(),
});

// Password Reset Token schemas @spec FEAT-003/DM-001
export const PasswordResetTokenSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  token: hexToken64,
  expires_at: z.string().datetime(),
  used_at: z.string().datetime().nullable().optional(),
});

// Password Reset request/response schemas @spec FEAT-003
export const PasswordResetRequestSchema = z.object({
  email: z.string().email().max(255),
});

export const PasswordResetConfirmSchema = z.object({
  token: hexToken64,
  new_password: z.string().min(12),
});

// Type exports
export type User = z.infer<typeof UserSchema>;
export type UserResponse = z.infer<typeof UserResponseSchema>;
export type RegisterRequest = z.infer<typeof RegisterRequestSchema>;
export type LoginRequest = z.infer<typeof LoginRequestSchema>;
export type TokenResponse = z.infer<typeof TokenResponseSchema>;
export type AccessTokenResponse = z.infer<typeof AccessTokenResponseSchema>;
export type ErrorResponse = z.infer<typeof ErrorResponseSchema>;
export type Session = z.infer<typeof SessionSchema>;
export type LoginAttempt = z.infer<typeof LoginAttemptSchema>;
export type EmailVerificationToken = z.infer<typeof EmailVerificationTokenSchema>;
export type PasswordResetToken = z.infer<typeof PasswordResetTokenSchema>;
export type PasswordResetRequest = z.infer<typeof PasswordResetRequestSchema>;
export type PasswordResetConfirm = z.infer<typeof PasswordResetConfirmSchema>;
