# Auto-generated by /data-contract-generator
# @spec FEAT-001/DM-002, FEAT-002/DM-002, FEAT-003/DM-001
# Do not edit manually - regenerate from specs

from datetime import datetime
from uuid import UUID
from re import fullmatch

from pydantic import BaseModel, EmailStr, Field, field_validator


class EmailVerificationTokenBase(BaseModel):
    """Base email verification token model. @spec FEAT-001/DM-002"""

    user_id: UUID


class EmailVerificationTokenInDB(EmailVerificationTokenBase):
    """Full email verification token as stored in database. @spec FEAT-001/DM-002"""

    id: UUID
    token: str = Field(..., min_length=64, max_length=64)
    expires_at: datetime
    used_at: datetime | None = None

    @field_validator("token")
    @classmethod
    def validate_token_format(cls, v: str) -> str:
        if not fullmatch(r"^[a-f0-9]{64}$", v):
            raise ValueError("Token must be 64 hex characters")
        return v

    class Config:
        from_attributes = True


class LoginAttemptBase(BaseModel):
    """Base login attempt model. @spec FEAT-002/DM-002"""

    email: EmailStr = Field(..., max_length=255)
    ip_address: str | None = None
    success: bool


class LoginAttemptInDB(LoginAttemptBase):
    """Full login attempt record. @spec FEAT-002/DM-002"""

    id: UUID
    created_at: datetime

    class Config:
        from_attributes = True


class PasswordResetTokenBase(BaseModel):
    """Base password reset token model. @spec FEAT-003/DM-001"""

    user_id: UUID


class PasswordResetTokenInDB(PasswordResetTokenBase):
    """Full password reset token as stored in database. @spec FEAT-003/DM-001"""

    id: UUID
    token: str = Field(..., min_length=64, max_length=64)
    expires_at: datetime
    used_at: datetime | None = None

    @field_validator("token")
    @classmethod
    def validate_token_format(cls, v: str) -> str:
        if not fullmatch(r"^[a-f0-9]{64}$", v):
            raise ValueError("Token must be 64 hex characters")
        return v

    class Config:
        from_attributes = True


# Request/Response models for Password Reset @spec FEAT-003

class PasswordResetRequestSchema(BaseModel):
    """Password reset request. @spec FEAT-003/API-001"""

    email: EmailStr = Field(..., max_length=255)


class PasswordResetConfirmSchema(BaseModel):
    """Password reset confirmation. @spec FEAT-003/API-002"""

    token: str = Field(..., min_length=64, max_length=64)
    new_password: str = Field(..., min_length=12)

    @field_validator("token")
    @classmethod
    def validate_token_format(cls, v: str) -> str:
        if not fullmatch(r"^[a-f0-9]{64}$", v):
            raise ValueError("Token must be 64 hex characters")
        return v
